server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: formato-service
          uri: lb://formato-service
          predicates:
            - Path=/api/formato/**
          filters:
            - StripPrefix=2
        - id: silabo-service
          uri: lb://microservicio-silabo
          predicates:
            - Path=/api/silabo/**
          filters:
            - StripPrefix=1
        - id: busqueda-curso-service
          uri: lb://microservicio-silabo
          predicates:
            - Path=/api/busqueda-curso/**
          filters:
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ 