spring:
  application:
    name: microservicio-silabo
  config:
    import: optional:configserver:http://localhost:8888

  r2dbc:
    url: r2dbc:mysql://localhost:3306/tallerweb
    username: modsil
    password: modsil.1
    pool:
      enabled: true
      max-size: 20
  cloud:
    compatibility-verifier:
      enabled: false
  #  discovery:
  #    enabled: false  # Desactiva el registro en Eureka
   
  webflux:
    format:
      streaming: true

server:
  port: 8083

eureka:
  client:
    enabled: true    # Para desactivar el cliente Eureka
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  #server:
  #  enabled: true




