spring:
  application:
    name: microservicio-Silabo
  config:
    import: optional:configserver:http://localhost:8888

  r2dbc:
    url: r2dbc:mysql://localhost:3306/proyecto_web
    username: ${env.DB_USER:root}
    password: ${env.DB_PASSWORD:Mensajer_01}
    pool:
      enabled: true
      max-size: 10
  cloud:
    discovery:
      enabled: false  # Desactiva el registro en Eureka
eureka:
  client:
    enabled: false    # Desactiva el cliente Eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    enabled: false
