spring:
  application:
    name: microservicio-Silabo
  config:
    import: optional:configserver:http://localhost:8888

  r2dbc:
    url: r2dbc:mysql://localhost:3306/proyecto_web
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    pool:
      enabled: true
      max-size: 20
  cloud:
    discovery:
      enabled: false  # Desactiva el registro en Eureka
  webflux:
    format:
      streaming: true
eureka:
  client:
    enabled: false    # Desactiva el cliente Eureka
    register-with-eureka: false
    fetch-registry: false
  server:
    enabled: false




